
phases:
  install:
    commands:
      - echo "[+] Scanning for security vulnerability within dependencies"
      # - pipenv check (if pipenv is installed and a Pipfile is in place)
      # - Alternatively: https://www.owasp.org/index.php/OWASP_Dependency_Check
  pre_build:
    commands:
      
      - echo "[+] Running tests..."
      - python -m pytest tests/ -v
  build:
    commands:
      
      
      - echo "Starting SAM packaging `date` in `pwd`"
  
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip'